language: python
python:
    - "2.7"
sudo: required
install:
    - pip install -r requirements.txt
    - pip install pycodestyle
    - pip install coveralls
    - pip install codecov
script:
    - find ./gotorrent -name \*.py -exec pycodestyle {} +
    - nosetests -v --with-coverage --cover-erase --cover-package=DS-GoTorrent
after_success:
    - coveralls
    - codecov
notifications:
email: false
